### ISSUE TITLE
Hostnames in local_posix_identities.csv

### ISSUE THREAD

**Issue by lasdem** [doksu/splunk_auditd#21]
In our environment uid and usernames are not uniquely assigned on each server. Therefore it happens that for example on server1 the uid 500 is assigned to userA and on server2 the uid 500 is assigned to userB. 
Would it be possible to have a hostname field in the lookup, that if empty means this specific uid is in general assinged the specific username, but for specific hosts (where hostname is set and matches) override    the user assignment. 

Example: 
uid,user,hostname
0,root,
1,system,
500,splunk,
500,usera,system1
500,userb,system2

In this example root is always uid 0 and system always 1. 
uid 500 is splunk for all systems except system1 and system2 (for example system3, ...)
uid 500 is usera on system1 and userb on system2.

**Comment by doksu** [comment]
I'm working on a potential solution to this issue for the next major release, however inconsistent uid assignment across hosts is the real issue. Please see: https://answers.splunk.com/answers/567272/why-is-my-linux-auditd-app-confusing-the-uids-with-1.html
