### ISSUE TITLE
Automatic sourcetype assigment for RAW or ENRICHED auditd log formats

### ISSUE THREAD

**Issue by litew** [doksu/splunk_auditd#30]
Hello,

does TA-linux_auditd support automatic sourcetype assigment for forwarded events?

I've installed TA-linux_auditd app on Splunk Heavy Forwarders, Indexers and Search Heads.

On endpoints, I use Splunk Universal Forwarders configured to send events to Heavy Forwarders, HFs in turn send events to Indexers.

Here is local/inputs.conf from Universal Forwarder:
```
[monitor:///var/log/audit/audit.log]
disabled = false
index = security
```

With these settings Splunk always assigns linux:audit sourcetype no matter which log format (RAW|ENRICHED) is set in auditd.conf.

Is there any way to make Splunk automatically set right sourcetype based on auditd log format?

Splunk version: 8.0.1
TA-linux_auditd version: 3.1.0

WBR,
litew

**Comment by doksu** [comment]
Best practice is to always explicitly specify a sourcetype in inputs.conf monitor stanzas.

RAW is the default log format, which corresponds to the default linux:audit sourcetype.

On hosts which are configured to use the ENRICHED log format, please explicitly specify the linux:audit:enriched sourcetype in the inputs.conf monitor stanza. If for some reason this isn't possible, consider creating a 'TRANSFORMS' prop on your HFs that points linux:audit sourcetyped events they receive to the https://github.com/doksu/splunk_auditd/blob/master/TA-linux_auditd/default/transforms.conf#L6 transform, which will dynamically change the sourcetype of ENRICHED events.

**Comment by litew** [comment]
Hi doksu,
sorry for the late reply.

I'll follow your advice and set linux:audit:enriched sourcetype for auditd ENRICHED log format.

Thank you!
