### ISSUE TITLE
Daily Linux Login Summary

### ISSUE THREAD

**Issue by doksu** [doksu/splunk_auditd#6]
It would be very useful to add the 'terminal' field to the "Daily Linux Login Summary" saved search, however ssh logins generate more than one entry (one for pty device and other for ssh), so we need to figure out the best way to approach adding the terminal field.

**Comment by ianconolly** [comment]
I found the canned report was incomplete. The account field was empty for successful logins and only displayed failures. I added a new type= and did some cosmetic renaming of columns.
Here is my search query:

eventtype=auditd_events type=USER_LOGIN OR type=USER_START | eval account=coalesce(acct,user) | eval time = strftime(_time,"%m-%d-%Y %H:%M:%S") | table time host terminal account src action | rename time AS Time host AS Hostname terminal AS Method account AS User src AS "Remote Host" action AS Result

**Comment by doksu** [comment]
Hi Ian,

Thanks very much for your feedback. The 'account' eval is used because in the case of known accounts that fail to login, the 'acct' field provides the user account, but in the case of successful logins, the acct field is unpopulated but 'user' (determined by the 'auid' field) is resolvable. So in the case of your report not populating the 'account' field for successful logins, this would seem to indicate that your posix_identities lookup doesn't have all the posix users in your organisation.

Version 2.0 of the app is due to be released on Splunkbase next Monday and it has a new feature where it automatically learns posix users in your organisation to supplement the local and directory lookups (and would fix this issue). If you have a test search head and would like to have a look at the new app in the interim, please download from github and let me know what you think. :)

Thanks,
Doksu

**Comment by doksu** [comment]
Forgot that I added 'terminal' field some time ago to this report.
